services:
  - name: choir-attendance-api
    type: web
    runtime: node
    env: node
    plan: free
    buildCommand: |
      cd server
      npm install
    startCommand: cd server && node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://rwibutsomo:s2qeSadSNLQ8Twvh@cluster0.j41ak.mongodb.net/choir_db?retryWrites=true&w=majority&appName=Cluster0


  - name: choir-attendance-tracker
    type: web
    runtime: static
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: ./client/build

    envVars:
      - key: REACT_APP_API_BASE
        value: "https://choir-attendance-api.onrender.com"